"""add guest column to users

Revision ID: 1985cd3713f1
Revises: 8afb6a9e2a48
Create Date: 2024-05-28 13:32:52.080667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1985cd3713f1'
down_revision = '8afb6a9e2a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('guest')

    # ### end Alembic commands ###
