"""add guests table

Revision ID: 885a7e68546c
Revises: f890ecc4b8d5
Create Date: 2024-05-17 09:44:19.809607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885a7e68546c'
down_revision = 'f890ecc4b8d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_guests_room_id_rooms')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests')
    # ### end Alembic commands ###
