"""add host_id column to room, add host model

Revision ID: b4ac297b49ac
Revises: cd638e9d8a11
Create Date: 2024-05-20 14:18:05.111631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ac297b49ac'
down_revision = 'cd638e9d8a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_hosts_room_id_rooms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hosts_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_rooms')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rooms_host_id_users', type_='foreignkey')
        batch_op.drop_column('host_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_users_room_id_rooms', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_host_id_hosts'), 'hosts', ['host_id'], ['id'])
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_users_host_id_hosts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_users_room_id_rooms', 'rooms', ['room_id'], ['id'])
        batch_op.drop_column('host_id')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_rooms_host_id_users', 'users', ['host_id'], ['id'])

    op.create_table('_alembic_tmp_rooms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), nullable=True),
    sa.Column('video_id', sa.INTEGER(), nullable=True),
    sa.Column('host_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name='fk_rooms_host_id_users'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name='fk_rooms_video_id_videos'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.drop_table('hosts')
    # ### end Alembic commands ###
